export const COLOR = {
  bg: "#EFE4CC",
  panel: "#FFFFFF",
  ink: "#1A1611",
  inkSoft: "#5B5240",
  border: "#DCCBA0",
  accent: "#C1560F",
  accentSoft: "#F4DEC0",
  gold: "#93661D",
  navy: "#152238",
  navyDeep: "#0F1930",
  cream: "#F3E9D4",
  creamSoft: "#C8BB98",
  seal: "#1F5C4A",
  sealSoft: "#DCEBE3",
  flagRed: "#A63A2E",
  flagRedSoft: "#F3DEDA",
};

export const FONT_IMPORT =
  "@import url('https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700&family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@500;600;700&display=swap');";

export const styles = {
  page: {
    minHeight: "100vh",
    background: COLOR.bg,
    fontFamily: "'IBM Plex Sans', 'Segoe UI', -apple-system, sans-serif",
    color: COLOR.ink,
  },
  container: { maxWidth: 1000, margin: "0 auto", padding: "24px 20px 60px" },
  headerBand: {
    background: `linear-gradient(135deg, ${COLOR.navy} 0%, ${COLOR.navyDeep} 100%)`,
    padding: "22px 28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
  },
  headerInner: { maxWidth: 1000, margin: "0 auto", display: "flex", alignItems: "center", justifyContent: "space-between", width: "100%" },
  eyebrow: { fontSize: 11, letterSpacing: "0.14em", fontWeight: 600, color: COLOR.accent, marginBottom: 6, textTransform: "uppercase" },
  h1: { fontFamily: "'Fraunces', Georgia, serif", fontSize: 26, fontWeight: 600, margin: 0, color: COLOR.cream, letterSpacing: "-0.01em" },
  h2: { fontFamily: "'Fraunces', Georgia, serif", fontSize: 20, fontWeight: 600, margin: "0 0 4px" },
  h3: { fontSize: 15, fontWeight: 600, margin: "0 0 4px", fontFamily: "'Fraunces', Georgia, serif" },
  sub: { fontSize: 13, color: COLOR.inkSoft, lineHeight: 1.5, maxWidth: 640, margin: "0 0 16px" },
  nav: { display: "flex", gap: 4 },
  navTab: (active) => ({
    padding: "8px 16px",
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    background: active ? COLOR.accent : "transparent",
    color: active ? "#fff" : COLOR.creamSoft,
    border: "none",
  }),
  panel: {
    background: COLOR.panel,
    border: `1px solid ${COLOR.border}`,
    borderRadius: 14,
    padding: 22,
    marginBottom: 20,
  },
  dataBar: { display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 16 },
  dataChip: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: COLOR.panel,
    border: `1px solid ${COLOR.border}`,
    borderRadius: 10,
    padding: "10px 14px",
    fontSize: 13,
  },
  dataChipLabel: { color: COLOR.inkSoft },
  dataChipValue: { fontWeight: 700, fontFamily: "'IBM Plex Mono', monospace" },
  uploadBox: {
    background: "#FCFBF8",
    border: `2px dashed ${COLOR.border}`,
    borderRadius: 12,
    padding: "20px 18px",
    display: "flex",
    alignItems: "center",
    gap: 14,
    cursor: "pointer",
    marginBottom: 12,
  },
  uploadIcon: {
    width: 38,
    height: 38,
    borderRadius: "50%",
    background: COLOR.accentSoft,
    color: COLOR.accent,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 18,
    flexShrink: 0,
  },
  primaryBtn: {
    background: COLOR.accent,
    color: "#fff",
    border: "none",
    borderRadius: 10,
    padding: "11px 20px",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  secondaryBtn: {
    background: "#fff",
    color: COLOR.accent,
    border: `1px solid ${COLOR.accent}`,
    borderRadius: 8,
    padding: "8px 14px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  errorBox: {
    background: "#FBEAE8",
    border: "1px solid #E3B8B2",
    color: "#8A3327",
    padding: "12px 14px",
    borderRadius: 8,
    fontSize: 13,
    marginBottom: 16,
    lineHeight: 1.5,
  },
  warnBox: {
    background: "#FBF2EC",
    border: "1px solid #E8D2BC",
    color: "#7A4A1E",
    padding: "12px 14px",
    borderRadius: 8,
    fontSize: 13,
    marginBottom: 16,
    lineHeight: 1.5,
  },
  table: { width: "100%", borderCollapse: "collapse", fontSize: 13 },
  th: { textAlign: "left", padding: "8px 10px", borderBottom: `2px solid ${COLOR.ink}`, fontSize: 12, color: COLOR.inkSoft, fontWeight: 600 },
  td: { padding: "8px 10px", borderBottom: `1px solid ${COLOR.border}`, verticalAlign: "top" },
  progressBarOuter: { marginTop: 12, height: 6, borderRadius: 3, background: COLOR.border, overflow: "hidden" },
  progressBarInner: { height: "100%", background: COLOR.accent, transition: "width 0.2s" },
  badge: (tone) => ({
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: 6,
    fontSize: 11,
    fontWeight: 700,
    background: tone === "red" ? COLOR.flagRedSoft : tone === "green" ? COLOR.sealSoft : "#eee",
    color: tone === "red" ? COLOR.flagRed : tone === "green" ? COLOR.seal : COLOR.inkSoft,
  }),
  scoreStamp: (tone) => ({
    display: "inline-flex",
    width: 36,
    height: 36,
    borderRadius: "50%",
    border: `2px solid ${tone}`,
    color: tone,
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'IBM Plex Mono', monospace",
    fontWeight: 700,
    fontSize: 12,
  }),
};

export function bandColor(band) {
  if (band === "Likely select") return COLOR.seal;
  if (band === "Borderline") return COLOR.gold;
  return COLOR.flagRed;
}
